executor: cluster-generic
jobs: 25
cores: 100
latency-wait: 60
printshellcmds: true

software-deployment-method:
  - apptainer

default-resources:
  - queue=CODBCB
  - gpus=0

cluster-generic-submit-cmd: "qsub -terse -cwd -j y -o snakemakeLogs -q {resources.queue} -pe smp {threads} -l ngpus={resources.gpus}"